---
debug: true
spring:
  jpa:
    hibernate:
      ddl-auto: create
      generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false
  security:
    user:
      name: marco
      password: polo
  datasource:
    url: "jdbc:h2:mem:mancala"
    driverClassName: org.h2.Driver

