---
debug: true
spring:
  jpa:
    hibernate:
    ddl-auto: create
    generate-ddl: true
  liquibase:
    enabled: false
  security:
    user:
      name: marco
      password: polo
#      role:
#    ignored: /**
#    basic:
#      enable: true
