---
version: "3.4"
services:
  app:
    image: org.shimomoto/mancala:latest
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    volumes:
      - ./src/deployment/application.properties:/config/application.properties
      - ./src/deployment/application-dev.yml:/config/application-dev.yml
      - datavolume:/data
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "localhost:8081/actuator/health 2>&1 | grep UP || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 25s
volumes:
  datavolume:
